# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: .bumpversion.cfg
      - id: end-of-file-fixer
        exclude: .bumpversion.cfg
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
#      - id: name-tests-test
#        exclude: ^utils/
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
        exclude: ^protobuf/
      - id: check-added-large-files
  - repo: https://github.com/google/yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        args: ['--style=.style.yapf', '--parallel', '--in-place']
        exclude: models/
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
